# Dockerfile.consumer

# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

# Сборка бинарника consumer
RUN CGO_ENABLED=0 GOOS=linux go build -o consumer ./cmd/consumer

# Stage 2: Runtime
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/consumer ./consumer
COPY --from=builder /app/migrations ./migrations

RUN apk add --no-cache ca-certificates

ENTRYPOINT ["./consumer"]